export enum TokenType {
  HEADING = 'HEADING',
  LINK = 'LINK',
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  CITATION = 'CITATION',
  COMMENT = 'COMMENT',
  META = 'META',
  ANCHOR = 'ANCHOR',
  VARIABLE_DECLARATION = 'VARIABLE_DECLARATION',
  VARIABLE_USE = 'VARIABLE_USE',
  EOF = 'EOF'
}